# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name : self-hosted-agent-pool

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo apt-get -y install zip'
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Free Trial(2d3fea03-0818-45fc-bf19-0ceb1579d3e2)'
    backendAzureRmResourceGroupName: 'resource-group-1'
    backendAzureRmStorageAccountName: 'mystorageaccount8488'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Free Trial(2d3fea03-0818-45fc-bf19-0ceb1579d3e2)'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'validate'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Free Trial(2d3fea03-0818-45fc-bf19-0ceb1579d3e2)'